package provider

import (
	"context"
	"time"

	cycle "github.com/cycleplatform/api-client-go"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func init() {
	RegisterDataSource(NewTLSCertificatesDataSource)
}

var (
	_ datasource.DataSource              = (*tlsCertificatesDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*tlsCertificatesDataSource)(nil)
)

// NewTLSCertificatesDataSource returns the cycle_tls_certificates data source.
func NewTLSCertificatesDataSource() datasource.DataSource {
	return &tlsCertificatesDataSource{}
}

type tlsCertificatesDataSource struct {
	client *CycleClient
}

type tlsCertificatesDataSourceModel struct {
	Certificates []tlsCertificateDataModel `tfsdk:"certificates"`
}

type tlsCertificateDataModel struct {
	ID           types.String `tfsdk:"id"`
	Domains      types.List   `tfsdk:"domains"`
	Expires      types.String `tfsdk:"expires"`
	UserSupplied types.Bool   `tfsdk:"user_supplied"`
	State        types.String `tfsdk:"state"`
	HubID        types.String `tfsdk:"hub_id"`
}

func (d *tlsCertificatesDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tls_certificates"
}

func (d *tlsCertificatesDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists user-supplied TLS certificates in the hub. Private material (`bundle`, `private_key`) is never returned.",
		Attributes: map[string]schema.Attribute{
			"certificates": schema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "User-supplied TLS certificates in the hub.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The unique ID of the TLS certificate.",
						},
						"domains": schema.ListAttribute{
							Computed:            true,
							ElementType:         types.StringType,
							MarkdownDescription: "Domains associated with the certificate.",
						},
						"expires": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Expiration timestamp of the certificate, as RFC3339.",
						},
						"user_supplied": schema.BoolAttribute{
							Computed:            true,
							MarkdownDescription: "Whether this certificate was uploaded instead of generated by the platform.",
						},
						"state": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The current state of the certificate.",
						},
						"hub_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "The ID of the hub this certificate belongs to.",
						},
					},
				},
			},
		},
	}
}

func (d *tlsCertificatesDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	d.client = clientFromDataSourceConfigure(req, resp)
}

func (d *tlsCertificatesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config tlsCertificatesDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	certs, err := fetchAllUserSuppliedCertificates(ctx, d.client)
	if err != nil {
		resp.Diagnostics.AddError("Error listing TLS certificates", err.Error())
		return
	}

	config.Certificates = make([]tlsCertificateDataModel, 0, len(certs))
	for _, cert := range certs {
		item, diags := tlsCertificateDataModelFromAPI(ctx, cert)
		resp.Diagnostics.Append(diags...)
		if resp.Diagnostics.HasError() {
			return
		}
		config.Certificates = append(config.Certificates, item)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}

func tlsCertificateDataModelFromAPI(ctx context.Context, cert cycle.TlsCertificate) (tlsCertificateDataModel, diag.Diagnostics) {
	var item tlsCertificateDataModel
	item.ID = types.StringValue(cert.Id)
	item.UserSupplied = types.BoolValue(cert.UserSupplied)
	item.State = types.StringValue(string(cert.State.Current))
	item.Expires = types.StringValue(cert.Expires.Format(time.RFC3339))
	if cert.HubId != nil && *cert.HubId != "" {
		item.HubID = types.StringValue(*cert.HubId)
	} else {
		item.HubID = types.StringNull()
	}

	domains, d := tlsCertificateDomainsFromAPI(ctx, cert.Domains)
	item.Domains = domains
	return item, d
}

func fetchAllUserSuppliedCertificates(ctx context.Context, client *CycleClient) ([]cycle.TlsCertificate, error) {
	const pageSize = 100

	var all []cycle.TlsCertificate
	for pageNumber := float32(1); ; pageNumber++ {
		number := pageNumber
		size := float32(pageSize)
		listResp, err := client.Client.GetUserSuppliedCertificatesWithResponse(ctx, &cycle.GetUserSuppliedCertificatesParams{
			Page: &cycle.PageParam{
				Number: &number,
				Size:   &size,
			},
		})
		if err != nil {
			return nil, err
		}
		if listResp.JSON200 == nil {
			return nil, apiError("listing TLS certificates", listResp.StatusCode(), listResp.JSONDefault)
		}

		all = append(all, listResp.JSON200.Data...)
		if len(listResp.JSON200.Data) < pageSize {
			return all, nil
		}
	}
}
