package provider

import (
	"context"
	"net/http"
	"time"

	cycle "github.com/cycleplatform/api-client-go"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func init() {
	RegisterResource(NewTLSCertificateResource)
}

var (
	_ resource.Resource                = (*tlsCertificateResource)(nil)
	_ resource.ResourceWithConfigure   = (*tlsCertificateResource)(nil)
	_ resource.ResourceWithImportState = (*tlsCertificateResource)(nil)
)

// NewTLSCertificateResource returns the cycle_tls_certificate resource.
func NewTLSCertificateResource() resource.Resource {
	return &tlsCertificateResource{}
}

type tlsCertificateResource struct {
	client *CycleClient
}

type tlsCertificateResourceModel struct {
	ID           types.String `tfsdk:"id"`
	Bundle       types.String `tfsdk:"bundle"`
	PrivateKey   types.String `tfsdk:"private_key"`
	Domains      types.List   `tfsdk:"domains"`
	Expires      types.String `tfsdk:"expires"`
	UserSupplied types.Bool   `tfsdk:"user_supplied"`
	State        types.String `tfsdk:"state"`
	HubID        types.String `tfsdk:"hub_id"`
}

func (r *tlsCertificateResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_tls_certificate"
}

func (r *tlsCertificateResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Uploads a user-supplied TLS certificate (`POST /v1/dns/tls/user-certificates`). " +
			"There is no update endpoint; changing `bundle` or `private_key` forces replacement.\n\n" +
			"Cycle has no hard delete. Destroy issues a `deprecate` job so the platform can fall back to " +
			"another certificate (or generate one) for the applicable domains.\n\n" +
			"After import, `bundle` and `private_key` are unset because the API does not return private material. " +
			"Set them in configuration and ignore them on `ImportStateVerify`.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The unique ID of the TLS certificate.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"bundle": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "PEM-encoded certificate bundle. Changing this forces a new certificate to be uploaded.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"private_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				MarkdownDescription: "The certificate's private key. Changing this forces a new certificate to be uploaded.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"domains": schema.ListAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "Domains associated with the certificate.",
			},
			"expires": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Expiration timestamp of the certificate, as RFC3339.",
			},
			"user_supplied": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether this certificate was uploaded instead of generated by the platform.",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The current state of the certificate (e.g. `live`, `new`, `processing`).",
			},
			"hub_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The ID of the hub this certificate belongs to.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *tlsCertificateResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = clientFromResourceConfigure(req, resp)
}

func (r *tlsCertificateResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	if r.client == nil {
		return
	}

	var plan tlsCertificateResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createResp, err := r.client.Client.UploadUserSuppliedCertificateWithResponse(ctx, cycle.UploadUserSuppliedCertificateJSONRequestBody{
		Bundle:     plan.Bundle.ValueString(),
		PrivateKey: plan.PrivateKey.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Error uploading TLS certificate", err.Error())
		return
	}
	if createResp.JSON201 == nil {
		addAPIError(&resp.Diagnostics, "uploading TLS certificate", createResp.StatusCode(), createResp.JSONDefault)
		return
	}

	resp.Diagnostics.Append(tlsCertificateResourceFromAPI(ctx, &plan, createResp.JSON201.Data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *tlsCertificateResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	if r.client == nil {
		return
	}

	var state tlsCertificateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	getResp, err := r.client.Client.GetUserSuppliedCertificateWithResponse(ctx, state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading TLS certificate", err.Error())
		return
	}
	if getResp.StatusCode() == http.StatusNotFound {
		resp.State.RemoveResource(ctx)
		return
	}
	if getResp.JSON200 == nil {
		addAPIError(&resp.Diagnostics, "reading TLS certificate", getResp.StatusCode(), getResp.JSONDefault)
		return
	}

	cert := getResp.JSON200.Data
	if tlsCertificateGone(cert) {
		resp.State.RemoveResource(ctx)
		return
	}

	// The API never returns bundle/private_key; keep whatever is already in state.
	resp.Diagnostics.Append(tlsCertificateResourceFromAPI(ctx, &state, cert)...)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *tlsCertificateResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError(
		"TLS certificate cannot be updated",
		"cycle_tls_certificate has no update endpoint. Changing bundle or private_key forces replacement.",
	)
}

func (r *tlsCertificateResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	if r.client == nil {
		return
	}

	var state tlsCertificateResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteResp, err := r.client.Client.CreateUserSuppliedCertificateJobWithResponse(ctx, state.ID.ValueString(), cycle.CreateUserSuppliedCertificateJobJSONRequestBody{
		Action: cycle.Deprecate,
	})
	if err != nil {
		resp.Diagnostics.AddError("Error deprecating TLS certificate", err.Error())
		return
	}
	if deleteResp.StatusCode() == http.StatusNotFound {
		return
	}
	if deleteResp.JSON202 == nil {
		addAPIError(&resp.Diagnostics, "deprecating TLS certificate", deleteResp.StatusCode(), deleteResp.JSONDefault)
		return
	}
	if job := deleteResp.JSON202.Data.Job; job != nil {
		if _, err := waitForJob(ctx, r.client, job.Id); err != nil {
			resp.Diagnostics.AddError("Error waiting for TLS certificate deprecation", err.Error())
		}
	}
}

func (r *tlsCertificateResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func tlsCertificateGone(cert cycle.TlsCertificate) bool {
	if cert.State.Current == cycle.TlsCertificateStateCurrentDeprecated {
		return true
	}
	return !cert.Events.Deleted.IsZero()
}

func tlsCertificateResourceFromAPI(ctx context.Context, model *tlsCertificateResourceModel, cert cycle.TlsCertificate) diag.Diagnostics {
	var diags diag.Diagnostics

	model.ID = types.StringValue(cert.Id)
	model.UserSupplied = types.BoolValue(cert.UserSupplied)
	model.State = types.StringValue(string(cert.State.Current))
	model.Expires = types.StringValue(cert.Expires.Format(time.RFC3339))
	if cert.HubId != nil && *cert.HubId != "" {
		model.HubID = types.StringValue(*cert.HubId)
	} else {
		model.HubID = types.StringNull()
	}

	domains, d := tlsCertificateDomainsFromAPI(ctx, cert.Domains)
	diags.Append(d...)
	model.Domains = domains

	return diags
}

func tlsCertificateDomainsFromAPI(ctx context.Context, domains *[]string) (types.List, diag.Diagnostics) {
	if domains == nil {
		return types.ListValueFrom(ctx, types.StringType, []string{})
	}
	return types.ListValueFrom(ctx, types.StringType, *domains)
}
